# Generated by Django 2.2.7 on 2019-11-28 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MG',
        ),
        migrations.DeleteModel(
            name='MK',
        ),
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
